#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;
using MLA_SIM;                       // InteractableObject, InteractableCatalog, AnimationSequenceRegistry
using MLA_SIM.Dooms;                 // InteractionPoint, AreaAnchor
using MLA_SIM.Dooms.Registries;      // Faction/AreaTag/InteractionPoint/AnimationState/Prop registries, SceneRegistrySO

namespace MLA_SIM.Dooms.EditorTools
{
    /// <summary>
    /// AREA 04 — A4.1. Exports the current DOOMS vocabulary (everything already
    /// registered) into a single machine- and human-readable manifest the LLM can
    /// read before authoring scene / interactable JSON, so it reuses existing ids
    /// instead of inventing duplicates.
    ///
    /// Outputs:
    ///   configs/scenarios/dooms/dooms_vocabulary.json   (canonical, fed to the LLM)
    ///   docs/Dooms/Vocabulary_Reference.md              (human-skimmable mirror)
    ///
    /// Read-only: this tool never mutates registries or assets. It also includes a
    /// "scene census" (counts of placed InteractionPoint / AreaAnchor /
    /// InteractableObject per tag/archetype in the open scene) so the LLM respects
    /// physical capacity when assigning roles.
    /// </summary>
    public static class DoomsVocabularyExporter
    {
        [MenuItem("DOOMS/Export Vocabulary", priority = 90)]
        public static void ExportVocabulary()
        {
            string projectRoot = Path.GetFullPath(Path.Combine(Application.dataPath, "..", "..", ".."));
            string jsonPath = Path.Combine(projectRoot, "configs", "scenarios", "dooms", "dooms_vocabulary.json");
            string mdPath   = Path.Combine(projectRoot, "docs", "Dooms", "Vocabulary_Reference.md");

            // ---- gather vocabulary from registries (editor-safe Instance getters) ----
            var factions       = GetFactionIds();
            var pointTags      = GetList(InteractionPointRegistrySO.Instance?.pointTags);
            var areaTags       = GetList(AreaTagRegistrySO.Instance?.areaTags);
            var animStates     = GetList(AnimationStateRegistrySO.Instance?.states);
            var sequences      = GetSequences();
            var props          = GetProps();
            var sceneIds       = SceneRegistrySO.Instance != null
                                     ? SceneRegistrySO.Instance.GetSceneIds().ToList()
                                     : new List<string>();

            var catalog        = FindFirstCatalog();
            var archetypes     = GetArchetypes(catalog);
            var items          = GetItems(catalog);
            var contextTags    = GetContextTagUnion(catalog);

            // ---- scene census (open scene) ----
            var pointCensus    = CensusByKey(UnityEngine.Object.FindObjectsByType<InteractionPoint>(FindObjectsSortMode.None)
                                     .Select(p => p != null ? p.pointTag : null));
            var areaCensus     = CensusByKey(UnityEngine.Object.FindObjectsByType<AreaAnchor>(FindObjectsSortMode.None)
                                     .Select(a => a != null ? a.areaTag : null));
            var objectCensus   = CensusByKey(UnityEngine.Object.FindObjectsByType<InteractableObject>(FindObjectsSortMode.None)
                                     .Select(o => o != null ? (!string.IsNullOrEmpty(o.archetypeId) ? o.archetypeId : o.objectName) : null));

            // ---- enriched authoring context ----
            var factionDetails  = GetFactionDetails();
            var relations       = GetRelations();
            var worldNarrative  = GetWorldNarrative(projectRoot);
            var agentsByFaction = GetAgentsByFaction();

            // ---- build JSON ----
            var sb = new StringBuilder();
            sb.AppendLine("{");
            sb.AppendLine("  \"_comment\": \"AUTO-GENERATED by DOOMS/Export Vocabulary. Paste this to the LLM with a narrative brief. Reuse these ids; declare any genuinely new ids in a top-level 'new' block in your authored JSON.\",");
            sb.AppendLine($"  \"generatedUtc\": \"{DateTime.UtcNow:O}\",");
            AppendStringArray(sb, "factions", factions, false);
            AppendFactionDetails(sb, factionDetails, relations);
            AppendStringArray(sb, "pointTags", pointTags, false);
            AppendStringArray(sb, "areaTags", areaTags, false);
            AppendStringArray(sb, "animationStates", animStates, false);
            AppendSequences(sb, sequences);
            AppendProps(sb, props);
            AppendArchetypes(sb, archetypes);
            AppendItems(sb, items);
            AppendStringArray(sb, "contextTags", contextTags, false);
            AppendStringArray(sb, "sceneIds", sceneIds, false);
            AppendWorldNarrative(sb, worldNarrative);
            AppendSceneSchema(sb);
            AppendCapacity(sb, agentsByFaction, pointCensus);
            sb.AppendLine("  \"sceneCensus\": {");
            AppendCensus(sb, "interactionPoints", pointCensus, false);
            AppendCensus(sb, "areaAnchors", areaCensus, false);
            AppendCensus(sb, "interactableObjects", objectCensus, true);
            sb.AppendLine("  }");
            sb.AppendLine("}");

            Directory.CreateDirectory(Path.GetDirectoryName(jsonPath));
            File.WriteAllText(jsonPath, sb.ToString(), new UTF8Encoding(false));

            // ---- build markdown mirror ----
            WriteMarkdown(mdPath, factions, factionDetails, relations, worldNarrative,
                          pointTags, areaTags, animStates, sequences, props,
                          archetypes, items, contextTags, sceneIds,
                          agentsByFaction, pointCensus, areaCensus, objectCensus);

            AssetDatabase.Refresh();
            Debug.Log($"[DOOMS][Vocabulary] Exported manifest → {jsonPath}\n  factions={factions.Count} pointTags={pointTags.Count} areaTags={areaTags.Count} " +
                      $"states={animStates.Count} sequences={sequences.Count} props={props.Count} archetypes={archetypes.Count} items={items.Count} scenes={sceneIds.Count}");
            EditorUtility.DisplayDialog("DOOMS Vocabulary Exported",
                $"Manifest written to:\nconfigs/scenarios/dooms/dooms_vocabulary.json\n\n" +
                $"factions {factions.Count} · pointTags {pointTags.Count} · areaTags {areaTags.Count} · " +
                $"states {animStates.Count} · sequences {sequences.Count} · props {props.Count} · " +
                $"archetypes {archetypes.Count} · items {items.Count} · scenes {sceneIds.Count}", "OK");
        }

        // ────────────────────────── gather helpers ──────────────────────────

        private static List<string> GetFactionIds()
        {
            var reg = FactionRegistrySO.Instance;
            if (reg == null || reg.factions == null) return new List<string>();
            return reg.factions.Where(f => f != null && !string.IsNullOrWhiteSpace(f.factionId))
                               .Select(f => f.factionId).Distinct().ToList();
        }

        private static List<string> GetList(List<string> src)
        {
            if (src == null) return new List<string>();
            return src.Where(s => !string.IsNullOrWhiteSpace(s)).Distinct().ToList();
        }

        private class SeqInfo { public string id; public List<string> stepStates = new List<string>(); public List<string> props = new List<string>(); }

        private static List<SeqInfo> GetSequences()
        {
            var result = new List<SeqInfo>();
            var reg = AnimationSequenceRegistry.Instance;
            if (reg == null || reg.sequences == null) return result;
            foreach (var s in reg.sequences)
            {
                if (s == null || string.IsNullOrWhiteSpace(s.sequenceId)) continue;
                var info = new SeqInfo { id = s.sequenceId };
                if (!string.IsNullOrEmpty(s.startState)) info.stepStates.Add(s.startState);
                foreach (var step in s.GetHoldSteps())
                {
                    if (step == null) continue;
                    if (!string.IsNullOrEmpty(step.stateName)) info.stepStates.Add(step.stateName);
                    if (!string.IsNullOrEmpty(step.propId) && !info.props.Contains(step.propId)) info.props.Add(step.propId);
                }
                if (!string.IsNullOrEmpty(s.endState)) info.stepStates.Add(s.endState);
                result.Add(info);
            }
            return result;
        }

        private class PropInfo { public string id; public string bone; }

        private static List<PropInfo> GetProps()
        {
            var result = new List<PropInfo>();
            var reg = PropRegistrySO.Instance;
            if (reg == null || reg.props == null) return result;
            foreach (var p in reg.props)
            {
                if (p == null || string.IsNullOrWhiteSpace(p.propId)) continue;
                result.Add(new PropInfo { id = p.propId, bone = string.IsNullOrEmpty(p.defaultBone) ? "RightHand" : p.defaultBone });
            }
            return result;
        }

        private static InteractableCatalog FindFirstCatalog()
        {
            var guids = AssetDatabase.FindAssets("t:InteractableCatalog");
            if (guids == null || guids.Length == 0) return null;
            return AssetDatabase.LoadAssetAtPath<InteractableCatalog>(AssetDatabase.GUIDToAssetPath(guids[0]));
        }

        private class ArchInfo { public string id; public List<string> contextTags = new List<string>(); }

        private static List<ArchInfo> GetArchetypes(InteractableCatalog catalog)
        {
            var result = new List<ArchInfo>();
            if (catalog == null || catalog.archetypes == null) return result;
            foreach (var a in catalog.archetypes)
            {
                if (a == null || string.IsNullOrWhiteSpace(a.archetypeId)) continue;
                var info = new ArchInfo { id = a.archetypeId };
                if (a.defaultContextTags != null)
                    info.contextTags = a.defaultContextTags.Where(t => !string.IsNullOrWhiteSpace(t)).ToList();
                result.Add(info);
            }
            return result;
        }

        private static List<string> GetItems(InteractableCatalog catalog)
        {
            if (catalog == null || catalog.items == null) return new List<string>();
            return catalog.items.Where(i => i != null && !string.IsNullOrWhiteSpace(i.itemId))
                                .Select(i => i.itemId).Distinct().ToList();
        }

        private static List<string> GetContextTagUnion(InteractableCatalog catalog)
        {
            var set = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            if (catalog != null && catalog.archetypes != null)
            {
                foreach (var a in catalog.archetypes)
                {
                    if (a?.defaultContextTags == null) continue;
                    foreach (var t in a.defaultContextTags)
                        if (!string.IsNullOrWhiteSpace(t)) set.Add(t);
                }
            }
            return set.OrderBy(s => s).ToList();
        }

        private static Dictionary<string, int> CensusByKey(IEnumerable<string> keys)
        {
            var d = new Dictionary<string, int>(StringComparer.Ordinal);
            foreach (var k in keys)
            {
                if (string.IsNullOrWhiteSpace(k)) continue;
                d.TryGetValue(k, out int c);
                d[k] = c + 1;
            }
            return d;
        }

        private class FactionDetailInfo { public string id; public string description; }
        private class RelationInfo      { public string from; public string to; public string relation; }

        private static List<FactionDetailInfo> GetFactionDetails()
        {
            var reg = FactionRegistrySO.Instance;
            if (reg == null || reg.factions == null) return new List<FactionDetailInfo>();
            return reg.factions.Where(f => f != null && !string.IsNullOrWhiteSpace(f.factionId))
                               .Select(f => new FactionDetailInfo { id = f.factionId, description = f.description ?? "" })
                               .ToList();
        }

        private static List<RelationInfo> GetRelations()
        {
            var result = new List<RelationInfo>();
            FactionRelationsSO rel = null;
            var guids = AssetDatabase.FindAssets("t:FactionRelationsSO");
            foreach (var g in guids)
            {
                rel = AssetDatabase.LoadAssetAtPath<FactionRelationsSO>(AssetDatabase.GUIDToAssetPath(g));
                if (rel != null) break;
            }
            if (rel == null) return result;
            foreach (var row in rel.rows)
            {
                if (row == null || string.IsNullOrWhiteSpace(row.fromFaction) || row.cells == null) continue;
                foreach (var cell in row.cells)
                {
                    if (cell == null || string.IsNullOrWhiteSpace(cell.toFaction)) continue;
                    result.Add(new RelationInfo { from = row.fromFaction, to = cell.toFaction, relation = cell.relation.ToString() });
                }
            }
            return result;
        }

        private static string GetWorldNarrative(string projectRoot)
        {
            string path = Path.Combine(projectRoot, "docs", "Dooms", "Scene_Universe.md");
            if (!File.Exists(path)) { Debug.LogWarning($"[DOOMS][Vocabulary] Scene_Universe.md not found at {path}"); return ""; }
            return File.ReadAllText(path, new UTF8Encoding(false));
        }

        private static Dictionary<string, int> GetAgentsByFaction()
        {
            return CensusByKey(UnityEngine.Object.FindObjectsByType<DoomsAgentTag>(FindObjectsSortMode.None)
                       .Select(t => t != null ? t.factionId : null));
        }

        // ────────────────────────── JSON writers ──────────────────────────

        private static string Esc(string s) =>
            (s ?? "").Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");

        private static void AppendStringArray(StringBuilder sb, string key, List<string> values, bool last)
        {
            string inner = string.Join(", ", values.Select(v => $"\"{Esc(v)}\""));
            sb.AppendLine($"  \"{key}\": [{inner}]{(last ? "" : ",")}");
        }

        private static void AppendSequences(StringBuilder sb, List<SeqInfo> seqs)
        {
            sb.AppendLine("  \"animationSequences\": [");
            for (int i = 0; i < seqs.Count; i++)
            {
                var s = seqs[i];
                string steps = string.Join(", ", s.stepStates.Select(x => $"\"{Esc(x)}\""));
                string props = string.Join(", ", s.props.Select(x => $"\"{Esc(x)}\""));
                sb.AppendLine($"    {{ \"id\": \"{Esc(s.id)}\", \"steps\": [{steps}], \"props\": [{props}] }}{(i < seqs.Count - 1 ? "," : "")}");
            }
            sb.AppendLine("  ],");
        }

        private static void AppendProps(StringBuilder sb, List<PropInfo> props)
        {
            sb.AppendLine("  \"props\": [");
            for (int i = 0; i < props.Count; i++)
                sb.AppendLine($"    {{ \"id\": \"{Esc(props[i].id)}\", \"bone\": \"{Esc(props[i].bone)}\" }}{(i < props.Count - 1 ? "," : "")}");
            sb.AppendLine("  ],");
        }

        private static void AppendArchetypes(StringBuilder sb, List<ArchInfo> arch)
        {
            sb.AppendLine("  \"objectArchetypes\": [");
            for (int i = 0; i < arch.Count; i++)
            {
                string tags = string.Join(", ", arch[i].contextTags.Select(x => $"\"{Esc(x)}\""));
                sb.AppendLine($"    {{ \"id\": \"{Esc(arch[i].id)}\", \"contextTags\": [{tags}] }}{(i < arch.Count - 1 ? "," : "")}");
            }
            sb.AppendLine("  ],");
        }

        private static void AppendItems(StringBuilder sb, List<string> items)
        {
            string inner = string.Join(", ", items.Select(v => $"\"{Esc(v)}\""));
            sb.AppendLine($"  \"items\": [{inner}],");
        }

        private static void AppendCensus(StringBuilder sb, string key, Dictionary<string, int> census, bool last)
        {
            string inner = string.Join(", ", census.OrderBy(kv => kv.Key).Select(kv => $"\"{Esc(kv.Key)}\": {kv.Value}"));
            sb.AppendLine($"    \"{key}\": {{ {inner} }}{(last ? "" : ",")}");
        }

        private static void AppendFactionDetails(StringBuilder sb, List<FactionDetailInfo> details, List<RelationInfo> relations)
        {
            sb.AppendLine("  \"factionDetails\": [");
            for (int i = 0; i < details.Count; i++)
            {
                var d = details[i];
                var rels = relations.Where(r => r.from == d.id).ToList();
                string relStr = string.Join(", ", rels.Select(r => $"{{ \"to\": \"{Esc(r.to)}\", \"relation\": \"{Esc(r.relation)}\" }}"));
                sb.AppendLine($"    {{ \"id\": \"{Esc(d.id)}\", \"description\": \"{Esc(d.description)}\", \"relations\": [{relStr}] }}{(i < details.Count - 1 ? "," : "")}");
            }
            sb.AppendLine("  ],");
        }

        private static void AppendWorldNarrative(StringBuilder sb, string narrative)
        {
            sb.AppendLine($"  \"worldNarrative\": \"{Esc(narrative)}\",");
        }

        private static void AppendSceneSchema(StringBuilder sb)
        {
            sb.AppendLine("  \"sceneAuthoringSchema\": {");
            sb.AppendLine("    \"_note\": \"Use ONLY ids from factions/pointTags/areaTags/animationStates. role count must not exceed capacity.pointSlotsByTag for that pointTag.\",");
            sb.AppendLine("    \"sceneFields\": [\"sceneId\",\"displayName\",\"description\",\"narrativePhase\",\"requiredFactions\",\"optionalFactions\",\"minAgentsPerFaction\",\"baseDurationSec\",\"tags\",\"phases\"],");
            sb.AppendLine("    \"phaseFields\": [\"phaseId\",\"type\",\"minDurationSec\",\"maxDurationSec\",\"requiredPercentage\",\"roles\"],");
            sb.AppendLine("    \"phaseTypes\": [\"Assemble\",\"Hold\",\"Confront\",\"Disperse\"],");
            sb.AppendLine("    \"roleFields\": [\"roleId\",\"factionId\",\"pointTag\",\"animationState\",\"count\",\"arrivalTolerance\",\"optional\"]");
            sb.AppendLine("  },");
        }

        private static void AppendCapacity(StringBuilder sb, Dictionary<string, int> agentsByFaction, Dictionary<string, int> pointSlotsByTag)
        {
            string agents = string.Join(", ", agentsByFaction.OrderBy(kv => kv.Key).Select(kv => $"\"{Esc(kv.Key)}\": {kv.Value}"));
            string slots  = string.Join(", ", pointSlotsByTag.OrderBy(kv => kv.Key).Select(kv => $"\"{Esc(kv.Key)}\": {kv.Value}"));
            sb.AppendLine("  \"capacity\": {");
            sb.AppendLine($"    \"agentsByFaction\": {{ {agents} }},");
            sb.AppendLine($"    \"pointSlotsByTag\": {{ {slots} }}");
            sb.AppendLine("  },");
        }

        // ────────────────────────── markdown mirror ──────────────────────────

        private static void WriteMarkdown(string mdPath,
            List<string> factions, List<FactionDetailInfo> factionDetails, List<RelationInfo> relations,
            string worldNarrative, List<string> pointTags, List<string> areaTags, List<string> animStates,
            List<SeqInfo> sequences, List<PropInfo> props, List<ArchInfo> archetypes, List<string> items,
            List<string> contextTags, List<string> sceneIds,
            Dictionary<string, int> agentsByFaction,
            Dictionary<string, int> pointCensus, Dictionary<string, int> areaCensus, Dictionary<string, int> objectCensus)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# DOOMS Vocabulary Reference");
            sb.AppendLine();
            sb.AppendLine("> *Auto-generated by `DOOMS/Export Vocabulary`. Do not hand-edit.*");
            sb.AppendLine();
            sb.AppendLine($"_Generated: {DateTime.UtcNow:u}_");
            sb.AppendLine();
            sb.AppendLine("## Factions");
            sb.AppendLine();
            foreach (var d in factionDetails)
            {
                sb.AppendLine($"### `{d.id}`");
                sb.AppendLine(d.description);
                var rels = relations.Where(r => r.from == d.id).ToList();
                if (rels.Count > 0) sb.AppendLine("Relations: " + string.Join(", ", rels.Select(r => $"{r.to}={r.relation}")));
                sb.AppendLine();
            }
            AppendMdList(sb, "Point Tags", pointTags);
            AppendMdList(sb, "Area Tags", areaTags);
            AppendMdList(sb, "Animation States", animStates);
            sb.AppendLine("## Animation Sequences");
            foreach (var s in sequences)
                sb.AppendLine($"- `{s.id}` — steps: {string.Join(" → ", s.stepStates)}{(s.props.Count > 0 ? $"  · props: {string.Join(", ", s.props)}" : "")}");
            sb.AppendLine();
            sb.AppendLine("## Props");
            foreach (var p in props) sb.AppendLine($"- `{p.id}` (bone: {p.bone})");
            sb.AppendLine();
            sb.AppendLine("## Object Archetypes");
            foreach (var a in archetypes) sb.AppendLine($"- `{a.id}`{(a.contextTags.Count > 0 ? $" — tags: {string.Join(", ", a.contextTags)}" : "")}");
            sb.AppendLine();
            AppendMdList(sb, "Items", items);
            AppendMdList(sb, "Context Tags", contextTags);
            AppendMdList(sb, "Scene Ids", sceneIds);
            sb.AppendLine("## Capacity (agents and point slots in open scene)");
            sb.AppendLine();
            sb.AppendLine("| Kind | ID | Count |");
            sb.AppendLine("|---|---|---|");
            foreach (var kv in agentsByFaction.OrderBy(k => k.Key)) sb.AppendLine($"| Agent (faction) | `{kv.Key}` | {kv.Value} |");
            foreach (var kv in pointCensus.OrderBy(k => k.Key))     sb.AppendLine($"| InteractionPoint slots | `{kv.Key}` | {kv.Value} |");
            sb.AppendLine();
            sb.AppendLine("## Scene Authoring Schema");
            sb.AppendLine();
            sb.AppendLine("Role `factionId` must be from **Factions** above. Role `pointTag` must be from **Point Tags** above.");
            sb.AppendLine("Role `count` must not exceed the **Capacity** `InteractionPoint slots` for that tag.");
            sb.AppendLine("Phase `type` ∈ `Assemble | Hold | Confront | Disperse`.");
            sb.AppendLine();
            sb.AppendLine("## Scene Census (placed instances in the open scene)");
            sb.AppendLine();
            sb.AppendLine("| Kind | Tag/Archetype | Count |");
            sb.AppendLine("|---|---|---|");
            foreach (var kv in pointCensus.OrderBy(k => k.Key))  sb.AppendLine($"| InteractionPoint | `{kv.Key}` | {kv.Value} |");
            foreach (var kv in areaCensus.OrderBy(k => k.Key))   sb.AppendLine($"| AreaAnchor | `{kv.Key}` | {kv.Value} |");
            foreach (var kv in objectCensus.OrderBy(k => k.Key)) sb.AppendLine($"| InteractableObject | `{kv.Key}` | {kv.Value} |");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(worldNarrative))
            {
                sb.AppendLine("## World Narrative (Scene_Universe.md)");
                sb.AppendLine();
                sb.Append(worldNarrative);
            }

            Directory.CreateDirectory(Path.GetDirectoryName(mdPath));
            File.WriteAllText(mdPath, sb.ToString(), new UTF8Encoding(false));
        }

        private static void AppendMdList(StringBuilder sb, string title, List<string> items)
        {
            sb.AppendLine($"## {title}");
            if (items.Count == 0) sb.AppendLine("_(none)_");
            else sb.AppendLine(string.Join(", ", items.Select(i => $"`{i}`")));
            sb.AppendLine();
        }
    }
}
#endif
